// src/features/posts/components/post-card.tsx
import type { JSX } from "react";
import { Link } from "@tanstack/react-router";
import CalendarIcon from "~icons/ph/calendar-blank";
import { Badge } from "~/components/ui/badge";

type PostCardProps = {
  title: string;
  description: string;
  date: string;
  tags: string[];
} & JSX.IntrinsicElements["div"];

export function PostCard({ title, description, date, tags, ...props }: PostCardProps) {
  return (
    <div
      className="bg-white/60 text-left transition-all group hover:bg-white"
      role="article"
      aria-labelledby="post-title"
      style={{ viewTransitionName: title }}
      {...props}
    >
      <div
        className="flex p-4 h-full focus:outline-none focus:ring focus:ring-pink-400 focus:ring-offset-2"
        aria-labelledby="post-title"
      >
        <div className="flex-1">
          <h3
            id="post-title"
            className="font-display md:text-base font-bold capitalize text-pink-950 group-hover:text-pink-700 transition-colors duration-100 ease-out"
          >
            {title}
          </h3>
          <p
            className="font-body leading-normal text-pink-950/70 text-sm"
            dangerouslySetInnerHTML={{ __html: description }}
          />
        </div>
        <div className="flex-1 flex flex-col gap-1 justify-between align-end">
          <div className="text-xs flex gap-1 justify-end text-pink-950/70">
            <CalendarIcon className="w-4 h-4 block" />
            <span>
              {new Date(date).toLocaleDateString("en-GB", {
                day: "numeric",
                month: "long",
                year: "numeric",
              })}
            </span>
          </div>
          <div className="flex gap-1 flex-wrap justify-end">
            {tags.map((tag) => (
              <Badge key={tag} variant="secondary">
                {tag}
              </Badge>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// src/components/card/PostCard.svelte
<script lang="ts">
	import CalendarIcon from "~icons/ph/calendar-blank";

	interface Props {
		title: string;
		description: string;
		href: string;
		date: Date;
		tags: string[];
	}

	const { title, description, href, date, tags }: Props = $props();
</script>

<div
	class="bg-white/60 text-left transition-all group hover:bg-white"
	role="article"
	aria-labelledby="post-title"
	style="view-transition-name: post-card-{href.split('/').pop()}"
>
	<a
		data-astro-prefetch
		rel="prefetch"
		{href}
		class="grid grid-rows-[auto_2rem_auto_2rem] p-4 h-full focus:outline-none focus:ring focus:ring-pink-400 focus:ring-offset-2"
		aria-labelledby="post-title"
	>
		<h3
			id="post-title"
			class="font-display md:text-base font-bold capitalize text-pink-950 group-hover:text-pink-700 transition-property-color duration-100 ease-out"
		>
			{title}
		</h3>
		<div
			class="text-xs flex gap-1 items-center text-pink-950/70 border-b border-pink-200/50"
		>
			<CalendarIcon class="w-4 h-4 block" />
			<span>
				{date.toLocaleDateString("en-GB", {
					day: "numeric",
					month: "long",
					year: "numeric",
				})}
			</span>
		</div>
		<p class="font-body leading-normal text-pink-950/70 pt-2 text-sm">
			{@html description}
		</p>
		<div class="flex gap-1 self-end flex-wrap">
			{#each tags as tag}
				<span
					class="text-xs font-mono text-pink-950/70 bg-pink-50/80 px-2 py-0.5"
				>
					#{tag}
				</span>
			{/each}
		</div>
	</a>
</div>
