// src/features/notes/components/search.tsx
import { useState, useMemo, useRef, useCallback, useEffect } from "react";
import { Link } from "@tanstack/react-router";
import type { Note } from "../lib/types";

interface SearchProps {
  notes: Note[];
  onSearch: (query: string, results: Note[]) => void;
}

export function Search({ notes, onSearch }: SearchProps) {
  const [query, setQuery] = useState("");
  const [activeIndex, setActiveIndex] = useState(-1);
  const listboxRef = useRef<HTMLUListElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const results = useMemo(() => {
    if (!query.trim()) return [];
    const q = query.toLowerCase();
    return notes
      .filter(
        (note) =>
          note.title.toLowerCase().includes(q) ||
          note.tags.some((t) => t.toLowerCase().includes(q)) ||
          note.description.toLowerCase().includes(q),
      )
      .slice(0, 10);
  }, [notes, query]);

  useEffect(() => {
    onSearch(query, results);
  }, [query, results, onSearch]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === "ArrowDown") {
        e.preventDefault();
        setActiveIndex((i) => Math.min(i + 1, results.length - 1));
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        setActiveIndex((i) => Math.max(i - 1, -1));
      } else if (e.key === "Escape") {
        setQuery("");
        inputRef.current?.blur();
      }
    },
    [results.length],
  );

  return (
    <div className="relative">
      <input
        ref={inputRef}
        type="text"
        value={query}
        onChange={(e) => {
          setQuery(e.target.value);
          setActiveIndex(-1);
        }}
        onKeyDown={handleKeyDown}
        placeholder="Search notes..."
        role="combobox"
        aria-expanded={results.length > 0}
        aria-controls="search-results-listbox"
        aria-activedescendant={activeIndex >= 0 ? `search-result-${activeIndex}` : undefined}
        className="w-full bg-white/60 border border-pink-200 px-4 py-2 text-sm font-body text-pink-950 placeholder:text-pink-950/40 focus:outline-none focus:ring focus:ring-pink-400 focus:ring-offset-2"
      />
      {results.length > 0 && (
        <ul
          ref={listboxRef}
          id="search-results-listbox"
          role="listbox"
          className="absolute z-10 w-full bg-white border border-pink-200 shadow-card mt-1 max-h-80 overflow-y-auto"
        >
          {results.map((note, i) => (
            <li
              key={note.slug}
              id={`search-result-${i}`}
              role="option"
              aria-selected={i === activeIndex}
              className={`border-b border-pink-100 last:border-b-0 ${
                i === activeIndex ? "bg-pink-100" : ""
              }`}
            >
              <Link
                to={`/notes/${note.slug}`}
                className="block px-4 py-3 text-sm font-body text-pink-950 hover:bg-pink-50 focus:outline-none focus:ring focus:ring-pink-400 focus:ring-inset"
              >
                <span className="font-medium">{note.title}</span>
                {note.description && (
                  <span className="block text-xs text-pink-950/60 mt-0.5 line-clamp-1">
                    {note.description}
                  </span>
                )}
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// src/components/notes/Search.svelte
<script lang="ts">
import Fuse from "fuse.js";
import { onMount } from "svelte";

interface Note {
	id: string;
	title: string;
	description?: string;
	category: string;
	tags: string[];
}

interface Props {
	notes: Note[];
	onSearch?: (filteredIds: string[] | null) => void;
}

let { notes, onSearch }: Props = $props();

let query = $state("");
let results: Fuse.FuseResult<Note>[] = $state([]);
let fuse: Fuse<Note>;

onMount(() => {
	fuse = new Fuse(notes, {
		keys: [
			{ name: "title", weight: 2 },
			{ name: "description", weight: 1 },
			{ name: "tags", weight: 1.5 },
		],
		threshold: 0.3,
		includeScore: true,
	});
});

$effect(() => {
	if (query.trim() && fuse) {
		results = fuse.search(query);
		onSearch?.(results.map((r) => r.item.id));
	} else {
		results = [];
		onSearch?.(null);
	}
});

const categoryLabels: Record<string, string> = {
	article: "Article",
	vault: "Vault",
	person: "Person",
	music: "Music",
};
</script>

<div class="relative">
	<div class="relative">
		<input
			type="text"
			placeholder="Search notes..."
			bind:value={query}
			class="w-full px-3 py-2 pl-11 rounded-xl border-[0.5px] border-pink-200 bg-white/60 focus:bg-white/80 focus:outline-none focus:ring focus:ring-pink-400 text-pink-950 placeholder:text-pink-950/40 text-sm"
		/>
		<svg
			class="absolute left-3.5 top-1/2 -translate-y-1/2 w-5 h-5 text-pink-950/40"
			fill="none"
			stroke="currentColor"
			viewBox="0 0 24 24"
		>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
			/>
		</svg>
		{#if query}
			<button
				type="button"
				aria-label="Clear search"
				onclick={() => (query = "")}
				class="absolute right-3 top-1/2 -translate-y-1/2 text-pink-950/40 hover:text-pink-950/70"
			>
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M6 18L18 6M6 6l12 12"
					/>
				</svg>
			</button>
		{/if}
	</div>

	{#if query && results.length > 0}
		<div
			class="absolute z-10 w-full mt-2 bg-white/90 backdrop-blur-sm rounded-xl border-[0.5px] border-pink-200 shadow-lg max-h-96 overflow-auto"
		>
			{#each results as result}
				<a
					href={`/notes/${result.item.id}`}
					class="block p-4 hover:bg-pink-50/50 transition-colors border-b border-pink-100 last:border-b-0"
				>
					<div class="flex items-start justify-between gap-2">
						<div>
							<h4 class="font-medium text-pink-950">{result.item.title}</h4>
							{#if result.item.description}
								<p class="text-sm text-pink-950/60 mt-1 line-clamp-2">
									{result.item.description}
								</p>
							{/if}
						</div>
						<span
							class="text-xs px-2 py-1 rounded-full bg-pink-100/50 text-pink-900 shrink-0"
						>
							{categoryLabels[result.item.category]}
						</span>
					</div>
				</a>
			{/each}
		</div>
	{:else if query}
		<div
			class="absolute z-10 w-full mt-2 bg-white/90 backdrop-blur-sm rounded-xl border border-dashed border-pink-200 p-4 text-center text-pink-950/50"
		>
			No results found
		</div>
	{/if}
</div>
